package mz.gov.mogovolas.expedientes.controller;
import jakarta.servlet.http.HttpServletRequest; import mz.gov.mogovolas.expedientes.entity.*; import mz.gov.mogovolas.expedientes.repository.*; import mz.gov.mogovolas.expedientes.service.*; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.io.IOException; import java.util.*; import java.util.stream.Collectors;
@RestController @RequestMapping("/api") public class ApiController {final ExpedienteService es;final ExpedienteRepository er;final SectorRepository sr;final UtilizadorRepository ur;final PapelRepository pr;final PermissaoRepository per;final AnexoService as;final AuditoriaRepository ar;final AuditoriaService audit; public ApiController(ExpedienteService e,ExpedienteRepository r,SectorRepository s,UtilizadorRepository u,PapelRepository p,PermissaoRepository pe,AnexoService a,AuditoriaRepository aa,AuditoriaService au){es=e;er=r;sr=s;ur=u;pr=p;per=pe;as=a;ar=aa;audit=au;}
@GetMapping("/dashboard") @PreAuthorize("hasAuthority('RELATORIO_GERAR') or hasAuthority('EXPEDIENTE_VISUALIZAR')") public Map<String,Object> dashboard(){return Map.of("indicadores",es.indicadores(),"estados",er.findAll().stream().collect(Collectors.groupingBy(x->x.getEstado().name(),Collectors.counting())));}
@GetMapping("/expedientes") @PreAuthorize("hasAuthority('EXPEDIENTE_VISUALIZAR')") public List<Expediente> expedientes(@RequestParam(required=false)String q){return es.listar(q);}
@PostMapping("/expedientes") @PreAuthorize("hasAuthority('EXPEDIENTE_CRIAR')") public ResponseEntity<Expediente> criar(@RequestBody Expediente e,Authentication a,HttpServletRequest r){var x=es.criar(e,a.getName());audit.registar(a.getName(),"CRIAR","EXPEDIENTE",x.getId(),r,"API");return ResponseEntity.status(201).body(x);}
@GetMapping("/expedientes/{id}") @PreAuthorize("hasAuthority('EXPEDIENTE_VISUALIZAR')") public Expediente detalhe(@PathVariable Long id){return es.obter(id);}
@PostMapping("/expedientes/{id}/tramitar") @PreAuthorize("hasAuthority('EXPEDIENTE_TRAMITAR')") public ResponseEntity<Void> tramitar(@PathVariable Long id,@RequestParam Long sectorDestino,@RequestParam(required=false)String observacao,Authentication a,HttpServletRequest r){es.tramitar(id,sectorDestino,observacao,a.getName());audit.registar(a.getName(),"TRAMITAR","EXPEDIENTE",id,r,"API");return ResponseEntity.ok().build();}
@PostMapping("/expedientes/{id}/receber") @PreAuthorize("hasAuthority('EXPEDIENTE_RECEBER')") public ResponseEntity<Void> receber(@PathVariable Long id,Authentication a){es.receber(id,a.getName());return ResponseEntity.ok().build();}
@PostMapping("/expedientes/{id}/despacho") @PreAuthorize("hasAuthority('DESPACHO_EMITIR')") public ResponseEntity<Void> despacho(@PathVariable Long id,@RequestParam String texto,Authentication a){es.despacho(id,texto,a.getName());return ResponseEntity.ok().build();}
@PostMapping("/expedientes/{id}/arquivar") @PreAuthorize("hasAuthority('EXPEDIENTE_ARQUIVAR')") public ResponseEntity<Void> arquivar(@PathVariable Long id){es.arquivar(id);return ResponseEntity.ok().build();}
@PostMapping("/expedientes/{id}/anexos") @PreAuthorize("hasAuthority('ANEXO_GERIR')") public Anexo anexo(@PathVariable Long id,@RequestParam MultipartFile ficheiro,Authentication a)throws IOException{return as.guardar(id,ficheiro,a.getName());}
@GetMapping("/anexos/{id}/download") @PreAuthorize("hasAuthority('EXPEDIENTE_VISUALIZAR')") public ResponseEntity<byte[]> download(@PathVariable Long id)throws IOException{var x=as.ler(id);return ResponseEntity.ok().contentType(MediaType.parseMediaType(Optional.ofNullable(x.anexo().getContentType()).orElse(MediaType.APPLICATION_OCTET_STREAM_VALUE))).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+x.anexo().getNomeOriginal().replace("\"","")+"\"").body(x.bytes());}
@GetMapping("/utilizadores") @PreAuthorize("hasAuthority('UTILIZADOR_GERIR')") public List<Utilizador> users(){return ur.findAll();}
@GetMapping("/papeis") @PreAuthorize("hasAuthority('PAPEL_GERIR')") public List<Papel> roles(){return pr.findAll();}
@GetMapping("/permissoes") @PreAuthorize("hasAuthority('PAPEL_GERIR')") public List<Permissao> perms(){return per.findAll();}
@GetMapping("/sectores") @PreAuthorize("hasAuthority('EXPEDIENTE_VISUALIZAR')") public List<Sector> sectors(){return sr.findAll();}
@GetMapping("/auditoria") @PreAuthorize("hasAuthority('AUDITORIA_CONSULTAR')") public List<Auditoria> audit(){return ar.findTop200ByOrderByDataHoraDesc();}
}
